## Numpy in Python ?
* It is abbrevation of Numerical Python. Numpy is for scientific Python.
* It helps to work with multiple arrays (1d,2d etc...) 

In [1]:
#Importing Numpy Library in Python
import numpy as np

#### Array is the main data Structure of Numpy.

* The array is collection of same type of data type .
* Array index starts from 0.

In [4]:
# Zero Dimensional Array 

arr = np.array(90) 
arr

array(90)

In [5]:
# 1 Dimension Array.

arr = np.array([1,2,3,4,5]) # 1d array only consist of 
arr

array([1, 2, 3, 4, 5])

In [85]:
# 2 Dimension Array
ary = np.array([[2,4,6,8,10],[11,12,13,14]])

<ipython-input-85-100b92d1d7b5>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  ary = np.array([[2,4,6,8,10],[11,12,13,14]])


In [36]:
ary.dtype

dtype('O')

In [84]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,19]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 19]])

In [20]:
# 3 dimension Array in Numpy. 
np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12]])

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

* The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single column, while a matrix refers to an array with multiple columns.

* With **ndim** attribute, dimension of arrays can be checked.

In [26]:
a = np.array([1,10,100])
a

array([  1,  10, 100])

In [29]:
a.ndim # Check the dimemnsions of the array.

1

* Shape :- checks for the no. of the rows and columns in the array.

In [30]:
a.shape

(3,)

* size :-  checks for the total no. of the elements in the array.

In [31]:
a.size

3

* dtype :- checks for the datatype of the array 

In [33]:
a.dtype

dtype('int32')

## Creating Numpy Arrays 

 * Arrays can be created using nesting of lists and using numpy library using np.array([])

In [37]:
ary = np.array([1,5,10]) #1 dimension array
ary

array([ 1,  5, 10])

In [38]:
type(ary) # Checking the type of array.

numpy.ndarray

In [40]:
ary.shape #checking the total number of rows in the array

(3,)

#### Note :-  If any one of the element in the array is float then the whole array will be converted to float automatically. This is because float has higher precedence than int.



In [44]:
ary1 = np.array([1,2,4.8,2,9]) #Entire array will be converted to float if one element is float.
ary1

array([1. , 2. , 4.8, 2. , 9. ])

* But it is possible to make it int or float if we specify the datatype while making array. 

In [43]:
ary = np.array([1,10,20,30,40.8],dtype = int)
ary

array([ 1, 10, 20, 30, 40])

In [46]:
type(ary1)

numpy.ndarray

In [47]:
type(ary)

numpy.ndarray

#### Zeros Array 

* It returns the array as n no. elements equal to zeroes

In [54]:
anr = np.zeros(8) #Returns the 8 array elements as array and default datatype is float.
anr

array([0., 0., 0., 0., 0., 0., 0., 0.])

 *  Similary we can also change the datatype by specifying it when creating the array.

In [57]:
amr = np.zeros(19,dtype =int)
amr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Ones Arrays

*  It returns the array as n no. elements equal to one and default datatype is float.

In [59]:
car = np.ones(12)
car 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
car1 = np.ones(10,dtype =int)
car1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

##### We can also create multiple dimensional arrays.

In [61]:
arr = np.ones([2,3],dtype =int) # 2 is rows and 3 is columns
arr

array([[1, 1, 1],
       [1, 1, 1]])

### Full Arrays 

* Full Arrays :- The full arrays are the type of arrays where we specify how many no. of rows and column we want and then we specify the number throughout the array.

In [64]:
ful_array = np.full([2,4],8) # 2 rows and 4 columns and 8 as value throughout the array.
ful_array

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

### Identity Arrays 

In [67]:
np.eye(4,4) #eye() :- 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Linear series

In [68]:
np.arange(1,25,2) # arange() :- arange() is used for when you want specify range from one point to another.
#                    for ex :- starting point :- 1 , end point :- 25, difference :- 2


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [71]:
np.linspace(1,10,5) # linspace() is used to create an array of equal number 
                    # start:- 1 , end :- 10 , total elements:- 5 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

* By default the data type is float   

In [72]:
np.linspace(10,25,7,dtype = int)

array([10, 12, 15, 17, 20, 22, 25])

### Distribution Arrays 

In [74]:
np.random.randint(1,20,5) #Random elements between 1 to 20 and we want 5 elements.

array([ 1,  3,  8, 14,  7])

### Array Indexing 

* Indexing in arrays and it's operation 
* How to access a particular element using indexes.

In [75]:
ary

array([ 1, 10, 20, 30, 40])

In [76]:
ary[0] # Accesing the first element.

1

In [77]:
ary[0:3] # Accessing the elements between index 0 to index 2 

array([ 1, 10, 20])

In [79]:
ary[-1] #Accessing the last element.

40

In [81]:
ary[::2] # Printing array from start to last and with the difference of elements as 2.

array([ 1, 20, 40])

In [96]:
arry = np.array([[10,20,30,40,50],[90,80,70,60,65],[11,22,33,44,55]])
arry

array([[10, 20, 30, 40, 50],
       [90, 80, 70, 60, 65],
       [11, 22, 33, 44, 55]])

In [97]:
arry.shape # No. of rows and columns

(3, 5)

In [98]:
arry[1] # Printing entire 0th row.

array([90, 80, 70, 60, 65])

In [99]:
arry[1,2] # Element with 1st row and 2nd element.

70

In [102]:
arry[0,1:] # Elements printing 0th row and from 1st column to end of column.

array([20, 30, 40, 50])

In [105]:
arry[:3,:3]

array([[10, 20, 30],
       [90, 80, 70],
       [11, 22, 33]])

In [108]:
arry > 30 #Boolean indexing in the array.

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True]])

### Subsets  

In [110]:
# Creating an array 
aray = np.random.randint(10,size = (4,4))
aray

array([[3, 7, 6, 8],
       [1, 8, 6, 9],
       [3, 2, 6, 7],
       [2, 5, 9, 1]])

In [118]:
sub_aray = aray[:,:3].copy()
sub_aray

array([[3, 7, 6],
       [1, 8, 6],
       [3, 2, 6],
       [2, 5, 9]])

In [119]:
sub_aray[0][0] = 55

In [122]:
sub_aray

array([[55,  7,  6],
       [ 1,  8,  6],
       [ 3,  2,  6],
       [ 2,  5,  9]])

### Reshape() function 

* reshape() function :-  reshape() function let us able to change the shape of array.

#### Note :- The shape of array is the dimensions of the array or the number of elements in each dimension. 

In [121]:
arry = np.arange(1,20)
ary

array([list([2, 4, 6, 8, 10]), list([11, 12, 13, 14])], dtype=object)

#####  Implementing reshape function.

* So, Here we can see that here we are using reshape function().

-->* from range 1 to 31 we have 30 elements in between 

In [139]:
arry = np.arange(1,31).reshape(2,15) 
arry

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [140]:
arry.shape # 2 rows and 15 columns. You have to set dimensions in terms of multiples of total elements.

(2, 15)

In [141]:
arry[0][9]

10

In [144]:
aty = arry.reshape(1,30) #Reshaping the array by reshape and giving the new dimensions.
aty

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

* We can also reshape directly.

In [145]:
ary = np.arange(1,11).reshape(2,5)
ary

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [146]:
ary.ndim

2

### Flattening of array 

* Flattening of array means that converting multiple dimension array into 1 dimension array. 
* We can use reshape(-1) and flatten() function for that.

In [148]:
a1 =np.arange(1,11).reshape(5,2)
a1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [150]:
a1.ndim

2

In [151]:
a1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
a1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Concatenation 

In [155]:
ary = np.arange(0,20).reshape(4,5)
ary

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [160]:
ary1 = np.random.randint(10,size =(5,4))
ary1

array([[0, 8, 3, 6],
       [9, 1, 4, 9],
       [7, 8, 5, 4],
       [5, 6, 9, 4],
       [5, 4, 3, 3]])

In [161]:
ary2 =np.random.randint(10,size =(5,4)) #Want 0 - 10 random elements and should have 5 rows and 4 columns.
ary2

array([[8, 8, 1, 9],
       [4, 3, 2, 6],
       [3, 9, 8, 2],
       [3, 4, 2, 8],
       [7, 6, 7, 9]])

In [162]:
ary1.ndim

2

In [163]:
ary2.ndim

2

In [164]:
np.concatenate([ary1,ary2])

array([[0, 8, 3, 6],
       [9, 1, 4, 9],
       [7, 8, 5, 4],
       [5, 6, 9, 4],
       [5, 4, 3, 3],
       [8, 8, 1, 9],
       [4, 3, 2, 6],
       [3, 9, 8, 2],
       [3, 4, 2, 8],
       [7, 6, 7, 9]])

In [166]:
np.concatenate([ary1,ary2],axis= 1) # If we want to concat them based on columns.

array([[0, 8, 3, 6, 8, 8, 1, 9],
       [9, 1, 4, 9, 4, 3, 2, 6],
       [7, 8, 5, 4, 3, 9, 8, 2],
       [5, 6, 9, 4, 3, 4, 2, 8],
       [5, 4, 3, 3, 7, 6, 7, 9]])

### Splitting 

In [167]:
ary1 = np.arange(1,11).reshape(5,2)
ary1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [175]:
np.split(ary1,[4,5])

[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([], shape=(0, 2), dtype=int32)]

### Sorting 

In [176]:
arr = np.random.randint(15,size = (3,5)) # Want 0 - 10 random elements and should have 5 rows and 4 columns.
arr

array([[ 0,  9,  3,  0,  2],
       [ 9, 13,  7,  2, 14],
       [12,  2,  6,  6,  5]])

In [179]:
arr.sort() # Sorted array in ascending order

arr

array([[ 0,  0,  2,  3,  9],
       [ 2,  7,  9, 13, 14],
       [ 2,  5,  6,  6, 12]])

In [181]:
-np.sort(-arr) # Sorted Array in descending order.

array([[ 9,  3,  2,  0,  0],
       [14, 13,  9,  7,  2],
       [12,  6,  6,  5,  2]])

In [183]:
np.sort(arr)[::1] # Sorted Array in Descending Order.

array([[ 0,  0,  2,  3,  9],
       [ 2,  7,  9, 13, 14],
       [ 2,  5,  6,  6, 12]])

* Just like Numbers we can also sort Strings in the arrays.

In [184]:
var = np.array(['Go','Java','C++','Python'])
var

array(['Go', 'Java', 'C++', 'Python'], dtype='<U6')

In [185]:
np.sort(var) # Ascending Order

array(['C++', 'Go', 'Java', 'Python'], dtype='<U6')

In [187]:
np.sort(var)[::-1] # Descending Order

array(['Python', 'Java', 'Go', 'C++'], dtype='<U6')

### Array Math

* One of the most useful use of array is that we can perform all arithmetical operations using it.

In [189]:
arry = np.random.randint(10,size = (5,2))
arry

array([[7, 1],
       [3, 4],
       [8, 4],
       [6, 6],
       [1, 6]])

In [195]:
print(type(arry))

<class 'numpy.ndarray'>


In [190]:
ary = np.random.randint(12,size = (6,2))
ary

array([[ 2,  4],
       [ 0,  9],
       [ 2, 10],
       [ 0,  0],
       [ 0,  6],
       [ 4,  7]])

* Adding 10 to both the arrays respectively.

In [197]:
np.add(arry,20)
arry

array([[7, 1],
       [3, 4],
       [8, 4],
       [6, 6],
       [1, 6]])

In [198]:
np.add(ary,10)

array([[12, 14],
       [10, 19],
       [12, 20],
       [10, 10],
       [10, 16],
       [14, 17]])

In [199]:
np.subtract(arry,5)

array([[ 2, -4],
       [-2, -1],
       [ 3, -1],
       [ 1,  1],
       [-4,  1]])

In [200]:
np.multiply(ary,2)

array([[ 4,  8],
       [ 0, 18],
       [ 4, 20],
       [ 0,  0],
       [ 0, 12],
       [ 8, 14]])